client_config_backend: settings
client_config:
  client_id: 653165253527-pf0hqjqcvj6dceg22vuthalo2n0bqm0r.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install